// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./AttestationRegistry.sol";
import "./ReputationTracker.sol";

/**
 * @title EWALending
 * @notice Core lending pool for Earned Wage Access.
 *         Upgraded for Full Protocol Privacy via ZK proofs (simulated via Unlink Relayer).
 */
contract EWALending {
    // ─── State ───────────────────────────────────────────────────────────
    address public owner;
    AttestationRegistry public attestationRegistry;
    ReputationTracker public reputationTracker;

    uint256 public maxLoanAmount = 5 ether;
    uint256 public totalLiquidity;

    // Confidential State
    // commitmentHash => is active
    mapping(bytes32 => bool) public activeCommitments;
    // nullifierHash => is spent
    mapping(bytes32 => bool) public usedNullifiers;

    // Semi-Private Public State for Auto-Deductions
    // address => total amount owed (principal + interest)
    mapping(address => uint256) public outstandingObligations;

    // ─── Events ──────────────────────────────────────────────────────────
    event LiquidityDeposited(address indexed provider, uint256 amount);

    // The key privacy events. Borrower address and amounts are hidden in bytes payload
    event ConfidentialLoanCreated(
        bytes32 indexed commitmentHash,
        bytes encryptedLoanData
    );

    event ConfidentialLoanRepaid(bytes32 indexed nullifierHash);

    // ─── Modifiers ───────────────────────────────────────────────────────
    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    // ─── Constructor ─────────────────────────────────────────────────────
    constructor(address _attestationRegistry, address _reputationTracker) {
        owner = msg.sender;
        attestationRegistry = AttestationRegistry(_attestationRegistry);
        reputationTracker = ReputationTracker(_reputationTracker);
    }

    // ─── Admin ───────────────────────────────────────────────────────────
    function setMaxLoanAmount(uint256 _max) external onlyOwner {
        maxLoanAmount = _max;
    }

    function depositLiquidity() external payable onlyOwner {
        require(msg.value > 0, "Zero deposit");
        totalLiquidity += msg.value;
        emit LiquidityDeposited(msg.sender, msg.value);
    }

    // ─── Confidential Borrowing ──────────────────────────────────────────

    /**
     * @notice Borrow MON confidentially.
     * @param _amount           Amount to borrow (transferred to user)
     * @param _totalOwed        Total expected repayment (principal + interest). Exposed semi-publicly for employers.
     * @param _commitmentHash   A hash of the secret loan metadata (salt, principal, borrower)
     * @param _encryptedData    Auditor view key encrypted payload `{borrower, principal, date}`
     */
    function borrowConfidential(
        uint256 _amount,
        uint256 _totalOwed,
        bytes32 _commitmentHash,
        bytes calldata _encryptedData
    ) external {
        // Attestation check remains public, but in a true ZK system this would be a proof
        require(
            attestationRegistry.isValid(msg.sender),
            "No valid attestation"
        );
        require(_amount > 0 && _amount <= maxLoanAmount, "Invalid loan amount");
        require(totalLiquidity >= _amount, "Insufficient liquidity");
        require(!activeCommitments[_commitmentHash], "Commitment exists");

        activeCommitments[_commitmentHash] = true;
        totalLiquidity -= _amount;

        // Expose obligation publicly so the employer can auto-deduct transparently
        outstandingObligations[msg.sender] += _totalOwed;

        // In true Unlink integration, this _amount is deposited into the Unlink Privacy Pool
        // For hackathon bridging, we transfer to the user, simulating the Relayer action.
        (bool success, ) = payable(msg.sender).call{value: _amount}("");
        require(success, "Transfer failed");

        emit ConfidentialLoanCreated(_commitmentHash, _encryptedData);
    }

    // ─── Confidential Repayment ──────────────────────────────────────────

    /**
     * @notice Manual/early repayment executed by the Unlink Relayer.
     * @param _borrower      The borrower settling the load
     * @param _nullifierHash The spent hash preventing double-repayment attacks
     * @param _proof         ZK proof generated by Unlink SDK (Mocked as bytes for MVP)
     */
    function repayConfidential(
        address _borrower,
        bytes32 _nullifierHash,
        bytes calldata _proof
    ) external payable {
        // ZK Verification:
        // require(verifier.verifyProof(_proof, _nullifierHash), "Invalid ZK proof");
        // For MVP, if proof length > 0 we assume it passed Relayer verification

        require(!usedNullifiers[_nullifierHash], "Loan already repaid");
        require(msg.value > 0, "Zero payment");

        usedNullifiers[_nullifierHash] = true;
        totalLiquidity += msg.value;

        // Decrease the public obligation hook
        if (outstandingObligations[_borrower] > msg.value) {
            outstandingObligations[_borrower] -= msg.value;
        } else {
            outstandingObligations[_borrower] = 0;
        }

        // Note: msg.sender is the Unlink Relayer paying gas, NOT the borrower!
        emit ConfidentialLoanRepaid(_nullifierHash);
    }

    // Allow contract to receive MON
    receive() external payable {
        totalLiquidity += msg.value;
    }
}
