/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestations"
      | "isValid"
      | "owner"
      | "registerAttestation"
      | "registerEmployer"
      | "registeredEmployers"
      | "revokeAttestation"
      | "setTrustedProvider"
      | "trustedProvider"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationRegistered"
      | "AttestationRevoked"
      | "EmployerRegistered"
      | "ProviderUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attestations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAttestation",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEmployer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredEmployers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedProvider",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isValid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEmployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredEmployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedProvider",
    data: BytesLike
  ): Result;
}

export namespace AttestationRegisteredEvent {
  export type InputTuple = [
    borrower: AddressLike,
    attestationHash: BytesLike,
    employerHash: BytesLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    attestationHash: string,
    employerHash: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    borrower: string;
    attestationHash: string;
    employerHash: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationRevokedEvent {
  export type InputTuple = [borrower: AddressLike];
  export type OutputTuple = [borrower: string];
  export interface OutputObject {
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployerRegisteredEvent {
  export type InputTuple = [employerHash: BytesLike];
  export type OutputTuple = [employerHash: string];
  export interface OutputObject {
    employerHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderUpdatedEvent {
  export type InputTuple = [newProvider: AddressLike];
  export type OutputTuple = [newProvider: string];
  export interface OutputObject {
    newProvider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        attestationHash: string;
        employerHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  isValid: TypedContractMethod<[_borrower: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAttestation: TypedContractMethod<
    [
      _attestationHash: BytesLike,
      _employerHash: BytesLike,
      _expiry: BigNumberish,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registerEmployer: TypedContractMethod<
    [_employerHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registeredEmployers: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  revokeAttestation: TypedContractMethod<
    [_borrower: AddressLike],
    [void],
    "nonpayable"
  >;

  setTrustedProvider: TypedContractMethod<
    [_provider: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedProvider: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        attestationHash: string;
        employerHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValid"
  ): TypedContractMethod<[_borrower: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAttestation"
  ): TypedContractMethod<
    [
      _attestationHash: BytesLike,
      _employerHash: BytesLike,
      _expiry: BigNumberish,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEmployer"
  ): TypedContractMethod<[_employerHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredEmployers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeAttestation"
  ): TypedContractMethod<[_borrower: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTrustedProvider"
  ): TypedContractMethod<[_provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedProvider"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AttestationRegistered"
  ): TypedContractEvent<
    AttestationRegisteredEvent.InputTuple,
    AttestationRegisteredEvent.OutputTuple,
    AttestationRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AttestationRevoked"
  ): TypedContractEvent<
    AttestationRevokedEvent.InputTuple,
    AttestationRevokedEvent.OutputTuple,
    AttestationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "EmployerRegistered"
  ): TypedContractEvent<
    EmployerRegisteredEvent.InputTuple,
    EmployerRegisteredEvent.OutputTuple,
    EmployerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderUpdated"
  ): TypedContractEvent<
    ProviderUpdatedEvent.InputTuple,
    ProviderUpdatedEvent.OutputTuple,
    ProviderUpdatedEvent.OutputObject
  >;

  filters: {
    "AttestationRegistered(address,bytes32,bytes32,uint256)": TypedContractEvent<
      AttestationRegisteredEvent.InputTuple,
      AttestationRegisteredEvent.OutputTuple,
      AttestationRegisteredEvent.OutputObject
    >;
    AttestationRegistered: TypedContractEvent<
      AttestationRegisteredEvent.InputTuple,
      AttestationRegisteredEvent.OutputTuple,
      AttestationRegisteredEvent.OutputObject
    >;

    "AttestationRevoked(address)": TypedContractEvent<
      AttestationRevokedEvent.InputTuple,
      AttestationRevokedEvent.OutputTuple,
      AttestationRevokedEvent.OutputObject
    >;
    AttestationRevoked: TypedContractEvent<
      AttestationRevokedEvent.InputTuple,
      AttestationRevokedEvent.OutputTuple,
      AttestationRevokedEvent.OutputObject
    >;

    "EmployerRegistered(bytes32)": TypedContractEvent<
      EmployerRegisteredEvent.InputTuple,
      EmployerRegisteredEvent.OutputTuple,
      EmployerRegisteredEvent.OutputObject
    >;
    EmployerRegistered: TypedContractEvent<
      EmployerRegisteredEvent.InputTuple,
      EmployerRegisteredEvent.OutputTuple,
      EmployerRegisteredEvent.OutputObject
    >;

    "ProviderUpdated(address)": TypedContractEvent<
      ProviderUpdatedEvent.InputTuple,
      ProviderUpdatedEvent.OutputTuple,
      ProviderUpdatedEvent.OutputObject
    >;
    ProviderUpdated: TypedContractEvent<
      ProviderUpdatedEvent.InputTuple,
      ProviderUpdatedEvent.OutputTuple,
      ProviderUpdatedEvent.OutputObject
    >;
  };
}
