/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EWALendingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeCommitments"
      | "attestationRegistry"
      | "borrowConfidential"
      | "depositLiquidity"
      | "maxLoanAmount"
      | "owner"
      | "repayConfidential"
      | "reputationTracker"
      | "setMaxLoanAmount"
      | "totalLiquidity"
      | "usedNullifiers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialLoanCreated"
      | "ConfidentialLoanRepaid"
      | "LiquidityDeposited"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeCommitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowConfidential",
    values: [BigNumberish, BytesLike, BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLoanAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "repayConfidential",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxLoanAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowConfidential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLoanAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repayConfidential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxLoanAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
}

export namespace ConfidentialLoanCreatedEvent {
  export type InputTuple = [
    commitmentHash: BytesLike,
    encryptedLoanData: BytesLike
  ];
  export type OutputTuple = [commitmentHash: string, encryptedLoanData: string];
  export interface OutputObject {
    commitmentHash: string;
    encryptedLoanData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialLoanRepaidEvent {
  export type InputTuple = [nullifierHash: BytesLike];
  export type OutputTuple = [nullifierHash: string];
  export interface OutputObject {
    nullifierHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityDepositedEvent {
  export type InputTuple = [provider: AddressLike, amount: BigNumberish];
  export type OutputTuple = [provider: string, amount: bigint];
  export interface OutputObject {
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EWALending extends BaseContract {
  connect(runner?: ContractRunner | null): EWALending;
  waitForDeployment(): Promise<this>;

  interface: EWALendingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeCommitments: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  attestationRegistry: TypedContractMethod<[], [string], "view">;

  borrowConfidential: TypedContractMethod<
    [
      _amount: BigNumberish,
      _commitmentHash: BytesLike,
      _encryptedData: BytesLike,
      _borrower: AddressLike,
      _recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  depositLiquidity: TypedContractMethod<[], [void], "payable">;

  maxLoanAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  repayConfidential: TypedContractMethod<
    [_nullifierHash: BytesLike, _proof: BytesLike],
    [void],
    "payable"
  >;

  reputationTracker: TypedContractMethod<[], [string], "view">;

  setMaxLoanAmount: TypedContractMethod<
    [_max: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalLiquidity: TypedContractMethod<[], [bigint], "view">;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeCommitments"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "attestationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowConfidential"
  ): TypedContractMethod<
    [
      _amount: BigNumberish,
      _commitmentHash: BytesLike,
      _encryptedData: BytesLike,
      _borrower: AddressLike,
      _recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositLiquidity"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "maxLoanAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "repayConfidential"
  ): TypedContractMethod<
    [_nullifierHash: BytesLike, _proof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "reputationTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMaxLoanAmount"
  ): TypedContractMethod<[_max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "ConfidentialLoanCreated"
  ): TypedContractEvent<
    ConfidentialLoanCreatedEvent.InputTuple,
    ConfidentialLoanCreatedEvent.OutputTuple,
    ConfidentialLoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialLoanRepaid"
  ): TypedContractEvent<
    ConfidentialLoanRepaidEvent.InputTuple,
    ConfidentialLoanRepaidEvent.OutputTuple,
    ConfidentialLoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityDeposited"
  ): TypedContractEvent<
    LiquidityDepositedEvent.InputTuple,
    LiquidityDepositedEvent.OutputTuple,
    LiquidityDepositedEvent.OutputObject
  >;

  filters: {
    "ConfidentialLoanCreated(bytes32,bytes)": TypedContractEvent<
      ConfidentialLoanCreatedEvent.InputTuple,
      ConfidentialLoanCreatedEvent.OutputTuple,
      ConfidentialLoanCreatedEvent.OutputObject
    >;
    ConfidentialLoanCreated: TypedContractEvent<
      ConfidentialLoanCreatedEvent.InputTuple,
      ConfidentialLoanCreatedEvent.OutputTuple,
      ConfidentialLoanCreatedEvent.OutputObject
    >;

    "ConfidentialLoanRepaid(bytes32)": TypedContractEvent<
      ConfidentialLoanRepaidEvent.InputTuple,
      ConfidentialLoanRepaidEvent.OutputTuple,
      ConfidentialLoanRepaidEvent.OutputObject
    >;
    ConfidentialLoanRepaid: TypedContractEvent<
      ConfidentialLoanRepaidEvent.InputTuple,
      ConfidentialLoanRepaidEvent.OutputTuple,
      ConfidentialLoanRepaidEvent.OutputObject
    >;

    "LiquidityDeposited(address,uint256)": TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
    LiquidityDeposited: TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
  };
}
