/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EWALending {
  export type LoanStruct = {
    id: BigNumberish;
    borrower: AddressLike;
    principal: BigNumberish;
    interest: BigNumberish;
    totalOwed: BigNumberish;
    totalRepaid: BigNumberish;
    scheme: BigNumberish;
    numInstallments: BigNumberish;
    installmentsPaid: BigNumberish;
    createdAt: BigNumberish;
    dueDate: BigNumberish;
    status: BigNumberish;
    collateral: BigNumberish;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrower: string,
    principal: bigint,
    interest: bigint,
    totalOwed: bigint,
    totalRepaid: bigint,
    scheme: bigint,
    numInstallments: bigint,
    installmentsPaid: bigint,
    createdAt: bigint,
    dueDate: bigint,
    status: bigint,
    collateral: bigint
  ] & {
    id: bigint;
    borrower: string;
    principal: bigint;
    interest: bigint;
    totalOwed: bigint;
    totalRepaid: bigint;
    scheme: bigint;
    numInstallments: bigint;
    installmentsPaid: bigint;
    createdAt: bigint;
    dueDate: bigint;
    status: bigint;
    collateral: bigint;
  };
}

export interface EWALendingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestationRegistry"
      | "borrow"
      | "borrowWithCollateral"
      | "borrowerLoanIds"
      | "defaultTermDays"
      | "depositLiquidity"
      | "getActiveLoans"
      | "getBorrowerLoanCount"
      | "getLoan"
      | "getOutstandingObligation"
      | "liquidate"
      | "loans"
      | "maxLoanAmount"
      | "owner"
      | "payrollRouter"
      | "repay"
      | "repayFromPayroll"
      | "reputationTracker"
      | "setMaxLoanAmount"
      | "setPayrollRouter"
      | "totalLiquidity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityDeposited"
      | "LoanCreated"
      | "LoanDefaulted"
      | "LoanFullyRepaid"
      | "LoanRepaid"
      | "PayrollRepayment"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attestationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowWithCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerLoanIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTermDays",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoanCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingObligation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "maxLoanAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payrollRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "repayFromPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxLoanAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPayrollRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLiquidity",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "attestationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowWithCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerLoanIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTermDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoanCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingObligation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxLoanAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payrollRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repayFromPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxLoanAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPayrollRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidity",
    data: BytesLike
  ): Result;
}

export namespace LiquidityDepositedEvent {
  export type InputTuple = [provider: AddressLike, amount: BigNumberish];
  export type OutputTuple = [provider: string, amount: bigint];
  export interface OutputObject {
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish,
    scheme: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principal: bigint,
    interest: bigint,
    scheme: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principal: bigint;
    interest: bigint;
    scheme: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFullyRepaidEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    amountPaid: BigNumberish,
    remaining: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    amountPaid: bigint,
    remaining: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    amountPaid: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollRepaymentEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amountApplied: BigNumberish,
    loansAffected: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    amountApplied: bigint,
    loansAffected: bigint
  ];
  export interface OutputObject {
    borrower: string;
    amountApplied: bigint;
    loansAffected: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EWALending extends BaseContract {
  connect(runner?: ContractRunner | null): EWALending;
  waitForDeployment(): Promise<this>;

  interface: EWALendingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestationRegistry: TypedContractMethod<[], [string], "view">;

  borrow: TypedContractMethod<
    [_amount: BigNumberish, _scheme: BigNumberish],
    [void],
    "nonpayable"
  >;

  borrowWithCollateral: TypedContractMethod<
    [_borrowAmount: BigNumberish],
    [void],
    "payable"
  >;

  borrowerLoanIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  defaultTermDays: TypedContractMethod<[], [bigint], "view">;

  depositLiquidity: TypedContractMethod<[], [void], "payable">;

  getActiveLoans: TypedContractMethod<
    [_borrower: AddressLike],
    [EWALending.LoanStructOutput[]],
    "view"
  >;

  getBorrowerLoanCount: TypedContractMethod<
    [_borrower: AddressLike],
    [bigint],
    "view"
  >;

  getLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [EWALending.LoanStructOutput],
    "view"
  >;

  getOutstandingObligation: TypedContractMethod<
    [_borrower: AddressLike],
    [bigint],
    "view"
  >;

  liquidate: TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        borrower: string;
        principal: bigint;
        interest: bigint;
        totalOwed: bigint;
        totalRepaid: bigint;
        scheme: bigint;
        numInstallments: bigint;
        installmentsPaid: bigint;
        createdAt: bigint;
        dueDate: bigint;
        status: bigint;
        collateral: bigint;
      }
    ],
    "view"
  >;

  maxLoanAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payrollRouter: TypedContractMethod<[], [string], "view">;

  repay: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  repayFromPayroll: TypedContractMethod<
    [_borrower: AddressLike],
    [void],
    "payable"
  >;

  reputationTracker: TypedContractMethod<[], [string], "view">;

  setMaxLoanAmount: TypedContractMethod<
    [_max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPayrollRouter: TypedContractMethod<
    [_router: AddressLike],
    [void],
    "nonpayable"
  >;

  totalLiquidity: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [_amount: BigNumberish, _scheme: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrowWithCollateral"
  ): TypedContractMethod<[_borrowAmount: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "borrowerLoanIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "defaultTermDays"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositLiquidity"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getActiveLoans"
  ): TypedContractMethod<
    [_borrower: AddressLike],
    [EWALending.LoanStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBorrowerLoanCount"
  ): TypedContractMethod<[_borrower: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [EWALending.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutstandingObligation"
  ): TypedContractMethod<[_borrower: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        borrower: string;
        principal: bigint;
        interest: bigint;
        totalOwed: bigint;
        totalRepaid: bigint;
        scheme: bigint;
        numInstallments: bigint;
        installmentsPaid: bigint;
        createdAt: bigint;
        dueDate: bigint;
        status: bigint;
        collateral: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxLoanAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payrollRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "repayFromPayroll"
  ): TypedContractMethod<[_borrower: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "reputationTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMaxLoanAmount"
  ): TypedContractMethod<[_max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPayrollRouter"
  ): TypedContractMethod<[_router: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LiquidityDeposited"
  ): TypedContractEvent<
    LiquidityDepositedEvent.InputTuple,
    LiquidityDepositedEvent.OutputTuple,
    LiquidityDepositedEvent.OutputObject
  >;
  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFullyRepaid"
  ): TypedContractEvent<
    LoanFullyRepaidEvent.InputTuple,
    LoanFullyRepaidEvent.OutputTuple,
    LoanFullyRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "PayrollRepayment"
  ): TypedContractEvent<
    PayrollRepaymentEvent.InputTuple,
    PayrollRepaymentEvent.OutputTuple,
    PayrollRepaymentEvent.OutputObject
  >;

  filters: {
    "LiquidityDeposited(address,uint256)": TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
    LiquidityDeposited: TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;

    "LoanCreated(uint256,address,uint256,uint256,uint8)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanDefaulted(uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanFullyRepaid(uint256)": TypedContractEvent<
      LoanFullyRepaidEvent.InputTuple,
      LoanFullyRepaidEvent.OutputTuple,
      LoanFullyRepaidEvent.OutputObject
    >;
    LoanFullyRepaid: TypedContractEvent<
      LoanFullyRepaidEvent.InputTuple,
      LoanFullyRepaidEvent.OutputTuple,
      LoanFullyRepaidEvent.OutputObject
    >;

    "LoanRepaid(uint256,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "PayrollRepayment(address,uint256,uint256)": TypedContractEvent<
      PayrollRepaymentEvent.InputTuple,
      PayrollRepaymentEvent.OutputTuple,
      PayrollRepaymentEvent.OutputObject
    >;
    PayrollRepayment: TypedContractEvent<
      PayrollRepaymentEvent.InputTuple,
      PayrollRepaymentEvent.OutputTuple,
      PayrollRepaymentEvent.OutputObject
    >;
  };
}
