/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PayrollRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositPayroll"
      | "employees"
      | "getLastPayrollReceived"
      | "getNextPayday"
      | "isRegistered"
      | "owner"
      | "registerEmployee"
      | "setNextPayday"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmployeeRegistered"
      | "PaydayUpdated"
      | "PayrollProcessed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositPayroll",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastPayrollReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextPayday",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerEmployee",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNextPayday",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLastPayrollReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextPayday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNextPayday",
    data: BytesLike
  ): Result;
}

export namespace EmployeeRegisteredEvent {
  export type InputTuple = [
    employee: AddressLike,
    lendingContract: AddressLike
  ];
  export type OutputTuple = [employee: string, lendingContract: string];
  export interface OutputObject {
    employee: string;
    lendingContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaydayUpdatedEvent {
  export type InputTuple = [employee: AddressLike, nextPayday: BigNumberish];
  export type OutputTuple = [employee: string, nextPayday: bigint];
  export interface OutputObject {
    employee: string;
    nextPayday: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollProcessedEvent {
  export type InputTuple = [
    employee: AddressLike,
    totalDeposit: BigNumberish,
    deducted: BigNumberish,
    forwarded: BigNumberish
  ];
  export type OutputTuple = [
    employee: string,
    totalDeposit: bigint,
    deducted: bigint,
    forwarded: bigint
  ];
  export interface OutputObject {
    employee: string;
    totalDeposit: bigint;
    deducted: bigint;
    forwarded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollRouter extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollRouter;
  waitForDeployment(): Promise<this>;

  interface: PayrollRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositPayroll: TypedContractMethod<
    [_employee: AddressLike, _nullifier: BytesLike, _proof: BytesLike],
    [void],
    "payable"
  >;

  employees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, bigint, bigint] & {
        registered: boolean;
        lendingContract: string;
        nextPayday: bigint;
        lastPayrollReceived: bigint;
      }
    ],
    "view"
  >;

  getLastPayrollReceived: TypedContractMethod<
    [_employee: AddressLike],
    [bigint],
    "view"
  >;

  getNextPayday: TypedContractMethod<
    [_employee: AddressLike],
    [bigint],
    "view"
  >;

  isRegistered: TypedContractMethod<
    [_employee: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerEmployee: TypedContractMethod<
    [_employee: AddressLike, _lendingContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setNextPayday: TypedContractMethod<
    [_employee: AddressLike, _timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositPayroll"
  ): TypedContractMethod<
    [_employee: AddressLike, _nullifier: BytesLike, _proof: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "employees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, bigint, bigint] & {
        registered: boolean;
        lendingContract: string;
        nextPayday: bigint;
        lastPayrollReceived: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastPayrollReceived"
  ): TypedContractMethod<[_employee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextPayday"
  ): TypedContractMethod<[_employee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[_employee: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerEmployee"
  ): TypedContractMethod<
    [_employee: AddressLike, _lendingContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNextPayday"
  ): TypedContractMethod<
    [_employee: AddressLike, _timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EmployeeRegistered"
  ): TypedContractEvent<
    EmployeeRegisteredEvent.InputTuple,
    EmployeeRegisteredEvent.OutputTuple,
    EmployeeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PaydayUpdated"
  ): TypedContractEvent<
    PaydayUpdatedEvent.InputTuple,
    PaydayUpdatedEvent.OutputTuple,
    PaydayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollProcessed"
  ): TypedContractEvent<
    PayrollProcessedEvent.InputTuple,
    PayrollProcessedEvent.OutputTuple,
    PayrollProcessedEvent.OutputObject
  >;

  filters: {
    "EmployeeRegistered(address,address)": TypedContractEvent<
      EmployeeRegisteredEvent.InputTuple,
      EmployeeRegisteredEvent.OutputTuple,
      EmployeeRegisteredEvent.OutputObject
    >;
    EmployeeRegistered: TypedContractEvent<
      EmployeeRegisteredEvent.InputTuple,
      EmployeeRegisteredEvent.OutputTuple,
      EmployeeRegisteredEvent.OutputObject
    >;

    "PaydayUpdated(address,uint256)": TypedContractEvent<
      PaydayUpdatedEvent.InputTuple,
      PaydayUpdatedEvent.OutputTuple,
      PaydayUpdatedEvent.OutputObject
    >;
    PaydayUpdated: TypedContractEvent<
      PaydayUpdatedEvent.InputTuple,
      PaydayUpdatedEvent.OutputTuple,
      PaydayUpdatedEvent.OutputObject
    >;

    "PayrollProcessed(address,uint256,uint256,uint256)": TypedContractEvent<
      PayrollProcessedEvent.InputTuple,
      PayrollProcessedEvent.OutputTuple,
      PayrollProcessedEvent.OutputObject
    >;
    PayrollProcessed: TypedContractEvent<
      PayrollProcessedEvent.InputTuple,
      PayrollProcessedEvent.OutputTuple,
      PayrollProcessedEvent.OutputObject
    >;
  };
}
