/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReputationTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_REPUTATION"
      | "TIER_SIZE"
      | "getReputation"
      | "hasReputation"
      | "lendingContract"
      | "owner"
      | "recordDefault"
      | "recordRepayment"
      | "reputations"
      | "setLendingContract"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ReputationUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER_SIZE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lendingContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDefault",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordRepayment",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingContract",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER_SIZE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingContract",
    data: BytesLike
  ): Result;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    borrower: string,
    oldScore: bigint,
    newScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    borrower: string;
    oldScore: bigint;
    newScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationTracker extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationTracker;
  waitForDeployment(): Promise<this>;

  interface: ReputationTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  TIER_SIZE: TypedContractMethod<[], [bigint], "view">;

  getReputation: TypedContractMethod<
    [_borrower: AddressLike],
    [bigint],
    "view"
  >;

  hasReputation: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lendingContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordDefault: TypedContractMethod<
    [_borrower: AddressLike, _loanAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordRepayment: TypedContractMethod<
    [_borrower: AddressLike, _loanAmount: BigNumberish, _onTime: boolean],
    [void],
    "nonpayable"
  >;

  reputations: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setLendingContract: TypedContractMethod<
    [_lending: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[_borrower: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasReputation"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lendingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDefault"
  ): TypedContractMethod<
    [_borrower: AddressLike, _loanAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordRepayment"
  ): TypedContractMethod<
    [_borrower: AddressLike, _loanAmount: BigNumberish, _onTime: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setLendingContract"
  ): TypedContractMethod<[_lending: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "ReputationUpdated(address,uint256,uint256,string)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
